<?php

namespace Database\Seeders;

use App\Models\PurchaseDetails;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PurchaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $purchase_details = [
            [
                'mode_id' => 1,
                'purchase_number' => '24-0526',
                'purchase_date' => '2025-12-12',
                'purchase_date_issued' =>'2025-12-12',
                'supplier_id' => 1,
                'article_id' => 1,
                'purchase_amount' => 1212.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'mode_id' => 2,
                'purchase_number' => '25-123',
                'purchase_date' => '2025-12-12',
                'purchase_date_issued' => '2025-12-12',
                 'supplier_id' => 2,
                'article_id' => 2,
                'purchase_amount' => 1000.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'mode_id' => 1,
                'purchase_number' => '25-001',
                'purchase_date' => '2025-01-15',
                'purchase_date_issued' => '2025-01-16',
                'supplier_id' => 1,
                'article_id' => 3,
                'purchase_amount' => 1500.25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'mode_id' => 2,
                'purchase_number' => '25-014',
                'purchase_date' => '2025-02-03',
                'purchase_date_issued' => '2025-02-05',
                'supplier_id' => 5,
                'article_id' => 1,
                'purchase_amount' => 825.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'mode_id' => 3,
                'purchase_number' => '25-028',
                'purchase_date' => '2025-03-22',
                'purchase_date_issued' => '2025-03-25',
                'supplier_id' => 3,
                'article_id' => 4,
                'purchase_amount' => 1120.75,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'mode_id' => 4,
                'purchase_number' => '25-045',
                'purchase_date' => '2025-04-10',
                'purchase_date_issued' => '2025-04-12',
                'supplier_id' => 6,
                'article_id' => 5,
                'purchase_amount' => 950.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'mode_id' => 2,
                'purchase_number' => '25-067',
                'purchase_date' => '2025-05-19',
                'purchase_date_issued' => '2025-05-21',
                'supplier_id' => 4,
                'article_id' => 2,
                'purchase_amount' => 1645.10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'mode_id' => 1,
                'purchase_number' => '25-089',
                'purchase_date' => '2025-06-02',
                'purchase_date_issued' => '2025-06-03',
                'supplier_id' => 2,
                'article_id' => 6,
                'purchase_amount' => 700.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'mode_id' => 4,
                'purchase_number' => '25-103',
                'purchase_date' => '2025-07-25',
                'purchase_date_issued' => '2025-07-26',
                'supplier_id' => 1,
                'article_id' => 4,
                'purchase_amount' => 2499.99,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'mode_id' => 3,
                'purchase_number' => '25-118',
                'purchase_date' => '2025-08-14',
                'purchase_date_issued' => '2025-08-15',
                'supplier_id' => 6,
                'article_id' => 1,
                'purchase_amount' => 530.40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'mode_id' => 2,
                'purchase_number' => '25-135',
                'purchase_date' => '2025-09-03',
                'purchase_date_issued' => '2025-09-05',
                'supplier_id' => 3,
                'article_id' => 5,
                'purchase_amount' => 1840.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'mode_id' => 1,
                'purchase_number' => '25-150',
                'purchase_date' => '2025-10-29',
                'purchase_date_issued' => '2025-10-30',
                'supplier_id' => 5,
                'article_id' => 6,
                'purchase_amount' => 999.99,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'mode_id' => 3,
                'purchase_number' => '25-162',
                'purchase_date' => '2025-11-04',
                'purchase_date_issued' => '2025-11-05',
                'supplier_id' => 4,
                'article_id' => 2,
                'purchase_amount' => 1210.60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'mode_id' => 4,
                'purchase_number' => '25-178',
                'purchase_date' => '2025-11-18',
                'purchase_date_issued' => '2025-11-19',
                'supplier_id' => 6,
                'article_id' => 3,
                'purchase_amount' => 2095.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'mode_id' => 1,
                'purchase_number' => '25-191',
                'purchase_date' => '2025-12-02',
                'purchase_date_issued' => '2025-12-03',
                'supplier_id' => 2,
                'article_id' => 5,
                'purchase_amount' => 745.75,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'mode_id' => 2,
                'purchase_number' => '25-205',
                'purchase_date' => '2025-12-15',
                'purchase_date_issued' => '2025-12-17',
                'supplier_id' => 1,
                'article_id' => 6,
                'purchase_amount' => 1320.00,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'mode_id' => 3,
                'purchase_number' => '25-219',
                'purchase_date' => '2025-12-22',
                'purchase_date_issued' => '2025-12-23',
                'supplier_id' => 5,
                'article_id' => 4,
                'purchase_amount' => 1675.30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            ];
            PurchaseDetails::insert($purchase_details);
    }
}
 